package ai.jiaolong.client.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** Roles in the jiaolong remote working system. */
enum class Role(val displayName: String) {
    AGENT("Agent"),
    USER("User"),
}

/** A task in the jiaolong system. Tasks always belong to a project. */
data class Task(
    val id: String,
    val title: String,
    val description: String,
    val workingDirectory: String,
    val updatedAt: String,
    val projectId: String = "",
    val assigneeAgent: String? = null,
    val agentWorking: Boolean = false,
    val state: String? = null,
    val tokenLimit: Int = 0,
    val totalTokenUsage: Int = 0,
    val comments: List<Comment> = emptyList(),
    /** Why the task failed; empty when there is no recorded failure. */
    val failureReason: String = "",
)

/**
 * A project in the jiaolong system. Tasks belong to a project; the current
 * project determines the context shown on the dashboard.
 *
 * [ordering] controls the order of the projects returned by the server
 * (ascending): the project with the least ordering value is the default
 * (current) project.
 *
 * [readonlyDirectories] is the project's readonly-directory catalog: the
 * directories a task of this project may select to mount read-only.
 */
data class Project(
    val id: String,
    val name: String,
    val description: String = "",
    val defaultTaskWorkingDirectory: String = "",
    val ordering: Int = 0,
    val readonlyDirectories: List<ReadonlyDirectory> = emptyList(),
)

/**
 * One readonly directory in a project's catalog. [alias] is the name of the
 * virtual root (`/readonly/<alias>`) the agent sees, [realPath] is the
 * absolute host directory it maps to, and [description] is a human-readable
 * hint shown in the UI. [id] is a stable catalog id assigned by the server
 * (empty until the readonly directory has been persisted).
 */
data class ReadonlyDirectory(
    val id: String = "",
    val alias: String,
    val realPath: String,
    val description: String = "",
)

/**
 * An LLM provider configured in the Jiaolong server settings.
 *
 * [index] is the position of this provider inside the server's `llmProviders`
 * array and is used to select it as the enabled provider.
 */
data class LlmProvider(
    val index: Int,
    val enabled: Boolean,
    val baseUrl: String,
    val model: String,
    val llmCooldownDuration: Int,
    val retryTimes: Int,
)

/**
 * A single server system health data frame returned by the Jiaolong Server
 * `GET /api/server/system-health` endpoint. [timestamp] is the Unix timestamp
 * in milliseconds when the frame was gathered and [cpuTemperatureCelsius] is
 * the CPU temperature in degrees Celsius at that moment.
 */
data class SystemHealthFrame(
    val timestamp: Long,
    val cpuTemperatureCelsius: Double,
)

/** A comment posted on a task. */
data class Comment(
    val id: String,
    val author: String,
    val role: Role,
    val content: String,
    val createdAt: Long,
    val linkedCommitId: String? = null,
)

/** A commit generated by an agent. */
data class Commit(
    val id: String,
    val message: String,
    val files: List<FileDiff> = emptyList(),
    val comments: List<CommitComment> = emptyList(),
    val approved: Boolean = false,
)

/** A single file diff inside a commit. */
data class FileDiff(
    val filePath: String,
    val lines: List<DiffLine> = emptyList(),
)

enum class DiffLineType {
    CONTEXT,
    ADDED,
    REMOVED,
}

/** A single line of a file diff. */
data class DiffLine(
    val oldLineNumber: Int? = null,
    val newLineNumber: Int? = null,
    val content: String,
    val type: DiffLineType = DiffLineType.CONTEXT,
)

/** A comment on a commit, either a general commit comment or a line comment. */
data class CommitComment(
    val id: String,
    val author: String,
    val content: String,
    val createdAt: Long,
    val lineNumber: Int? = null,
)

/**
 * The persisted session history of a task, returned by the Jiaolong Server
 * `GET /api/tasks/{id}/session-history` endpoint. It mirrors the JSON file the
 * agent writes into `~/.jiaolong/sessions` while working on a task.
 */
@Serializable
data class SessionHistory(
    @SerialName("creationTimestamp") val creationTimestamp: String? = null,
    @SerialName("sessionId") val sessionId: String? = null,
    @SerialName("taskId") val taskId: String? = null,
    @SerialName("fileLocation") val fileLocation: String? = null,
    @SerialName("agentTurns") val agentTurns: List<SessionTurn> = emptyList(),
)

/** A single turn in a session history file: either a message or a slash
 *  command (both identified by the `type` field). */
@Serializable
data class SessionTurn(
    val type: String? = null,
    val message: SessionMessage? = null,
    val command: String? = null,
)

/**
 * An LLM message inside a session turn. [content] can be a plain string or an
 * array of content parts (OpenAI style); [toolCalls] and [reasoningContent]
 * mirror the corresponding fields of the agent's persisted message objects and
 * are kept as raw [JsonElement]s so any server-side shape can be rendered.
 */
@Serializable
data class SessionMessage(
    val role: String? = null,
    val content: JsonElement? = null,
    @SerialName("reasoning_content") val reasoningContent: JsonElement? = null,
    @SerialName("tool_call_id") val toolCallId: String? = null,
    @SerialName("tool_calls") val toolCalls: List<JsonElement>? = null,
)
